spring.application.name=AuthenticationService

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

jwt.token.secret=${JWT_SECRET}
jwt.token.expired=${JWT_EXPIRATION:360000}

JWT_REFRESH_SECRET=KrFVFRAei4GDxfLb9LTzgC0yngRZ3m8Clgn0X37GuWg=
JWT_REFRESH_EXPIRATION=604800000