spring.application.name=AuthenticationService

spring.datasource.url=jdbc:postgresql://localhost:5432/authentication
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}

jwt.refresh.secret=${JWT_REFRESH_SECRET}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}